Do not set UIWindow bounds
square/SuperDelegate pull request #22
Opened 2017-12-21 15:46 UTC by benjohnde

Closes #14 

Just grabbed the low hanging fruit and adjusted the deployment target as well as the removal of settings the bounds to `UIScreen.bounds` programmatically.

2017-12-21 16:58 UTC, dfed requested changes
The side-effect of this change is that calling `setup(mainWindow:)` no longer sets the window size. So if clients have code that assumes the VC installed in the window has a non-zero size, that code will break.

That makes this change a breaking one. Before merging this, I'd like to do some investigation into when the window is set, and see if we can build API around that lifecycle.

That said, it looks like View Controllers installed in the size-zero window are the right size. So, maybe we're fine? Let's do a bit more investigation before we merge this.

2017-12-21 16:58 UTC, dfed commented on Sources/SuperDelegate.swift
> -        mainWindow.frame = UIScreen.main.bounds
I just tested this line on an iOS 8 simulator (plus iPad and a few others sims). I'm shocked this works. But, it does! So let's back out the platform bump.

2017-12-22 10:02 UTC, benjohnde commented
Removed the platform bump. Ready to merge from my side.

This PR fixes #14.

2017-12-22 15:38 UTC, dfed commented
This looks good to me! I'd like some confirmation from known adopters that this doesn't break anything on their side (it shouldn't, but I'm a little nervous changing this). @mthole @efirestone can you take a look and see if this change would impact your apps?

2024-05-04 06:28 UTC, closed without merging